# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# Default values for irods-postgres.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: postgres
  tag: "10.12"
  pullPolicy: IfNotPresent

backup:
  enable: true
  crontab: "0 5 * * *"

# will invoke a DB restore when set
restoreDB: false

# declares what cluster this is running on
isAWS: false

dataMountPath: /var/lib/postgresql/data
dataMountSubPath: /db_data
accessMode: "ReadWriteOnce"

adminUser: "someuser"
adminPassword: ""
mountSubPath: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

storage:
  create: false
  name: vol
  claimName: pvc
  size: 1Gi
  accessMode: "ReadWriteMany"
  mountPoint: /somedir

backupSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 1234

shmSize: 1Gi

resources:
  limits:
    memory: 3Gi
    cpu: 1000m
  requests:
    memory: 1Gi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
