# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "irods-rabbitmq.fullname" . }}
  labels:
    {{- include "irods-rabbitmq.labels" . | nindent 4 }}
    type: queue
spec:
  serviceName: {{ include "irods-rabbitmq.fullname" . }}
  selector:
    matchLabels:
      {{- include "irods-rabbitmq.selectorLabels" . | nindent 6 }}
      type: queue
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "irods-rabbitmq.selectorLabels" . | nindent 8 }}
        type: queue
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-rbtmq-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "irods-rabbitmq.fullname" . }}-configmap
          env:
            - name: QUEUE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "irods-rabbitmq.fullname" . }}-secrets
                  key: queue_user
            - name: QUEUE_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "irods-rabbitmq.fullname" . }}-secrets
                  key: queue_pw
            - name: QUEUE_ADMIN_PW
              valueFrom:
                secretKeyRef:
                  name: {{ include "irods-rabbitmq.fullname" . }}-secrets
                  key: queue_admin_pw
          ports:
            - name: mgt-port
              protocol: TCP
              containerPort: {{ .Values.service.target_port }}
            - name: queue-port
              protocol: TCP
              containerPort: {{ .Values.networking.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.storage.name }}
              mountPath: {{ .Values.storage.mountPoint }}
      volumes:
        - name: {{ .Values.storage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.claimName }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
