---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "irods-postgres.fullname" . }}
  labels:
    {{- include "irods-postgres.labels" . | nindent 4 }}
    type: dbms
spec:
  serviceName: {{ include "irods-postgres.fullname" . }}
  selector:
    matchLabels:
      {{- include "irods-postgres.selectorLabels" . | nindent 6 }}
      type: dbms
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "irods-postgres.selectorLabels" . | nindent 8 }}
        type: dbms
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "irods-postgres.fullname" . }}
{{/*          command: ['/bin/sh', '-c', 'while true; do date; sleep 3600; done']*/}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: POSTGRES_USER
            value: {{ .Values.adminUser }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.adminPassword }}
          - name: PGDATA
            value: {{ .Values.dataMountPath }}{{ .Values.dataMountSubPath }}
          ports:
            - name: postgres-port
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ .Values.storage.name }}
            mountPath: {{ .Values.dataMountPath }}
          {{- if .Values.shmSize }}
          - name: dshm
            mountPath: /dev/shm
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.shmSize }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSize }}
        {{- end }}
        - name: {{ .Values.storage.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-postgres.fullname" . }}-pvc
